name: 'abapVersion'
description: 'Extract abapGit repository version'
inputs:
  token:
    description: 'Github token'
    required: true
  repoFullName:
    description: 'Repository'
    required: false
  branch:
    description: 'Repository branch'
    required: false
outputs:
  version:
    description: 'abapGit repository version'
runs:
  using: 'node20'
  main: 'index.js'